### ISSUE TITLE
Replacing Snipcart With a Self-coded and Custom Shop

### ISSUE THREAD

**Issue by codesport** [notrab/headless-dropshipping-starter#76]
Guys,

Great piece of software you've put together 🎉 

**I need to ask 2 questions before jumping down this rabbit hole:**

1. I'm using Next.js. Is it non-trivial and easy to replace your Snipcart integration with my own custom built e-commerce site?  If so, any guidance on where to start?  The Printful "docs" just have API endpoints! 

2. If I opted to instead to use an e-commerce CMS like [Sanity.io](https://www.sanity.io/solution/e-commerce), am I asking for maximum pain?

Seems like option 1 might be easiest, but would love some expert guidance!

**The use case is a t-shirt store where** 

1. Users can upload their own  artwork for printing on t-shirts!

2.  Store sends the image and order to Printful for fulfilment and shipping

**Several folks on reddit have the same  or similar use case. But they've gotten no clear answers or direction from Printful:**

https://www.reddit.com/r/printful/comments/t5owwx/i_need_to_send_orders_to_printful_through_their/

https://www.reddit.com/r/printful/comments/m2nqa1/has_anyone_used_the_printful_api_with_their_own/

https://www.reddit.com/r/printful/comments/u0oscd/two_question_about_the_printful_api/

https://www.reddit.com/r/printful/comments/a6w2fa/can_someone_make_an_in_depth_tutorial_on_how_to/

**Comment by notrab** [comment]
Hey @codesport 

Thanks so much for your answer. Let me try to answer this as best as I can.

> I'm using Next.js. Is it non-trivial and easy to replace your Snipcart integration with my own custom built e-commerce site? If so, any guidance on where to start? The Printful "docs" just have API endpoints!

This isn't impossible but you'll have a lot more to manage probably. Snipcart provides webhooks for when the address changes for shipping so Printful can calculate the best price and tax. 

You can of course use something like Shopify which has a native Printful integration, but I wanted to build something here that was more custom, and developer friendly. If you haven't worked with APIs before, then this might be a quicker route if you need to ship fast.

But building something custom is more fun, right? 😉 

> If I opted to instead to use an e-commerce CMS like [Saniity.io](https://www.sanity.io/solution/e-commerce), am I asking for maximum pain?

This question has came up a few times before, and it's something that's doable. I opted not to do it for simplicity sake (get products from printful, put them on a single page) but it's not exactly scalable with an index page full of products.

What you could do is create a schema with Sanity and have a field for "Printful ID" that when creating records you fill in that field with the ID of the product from Printful... Then on the frontend you fetch from both, using Sanity as the main source to build pages, and then enhance the page using the Printful product you fetched using the "Printful ID" response from Sanity.

This way you could upload reviews, product descriptions, more images etc.

As for your other requirements, this is something I started working on myself many years ago but abandoned. 

> Users can upload their own artwork for printing on t-shirts!

I actually started doing something similar whereby users could enter a tweet URL and I'd print it on a tee. I never shipped it. I was too scared there would be legal implications, probably even more so now with Musk on the horizon.

> Store sends the image and order to Printful to fulfilment and shipping

Printful have an API for this. You can submit an image and they return a preview. It's really f'ing cool.

I hope this answers your questions. I haven't had much opportunity since leaving my full time job to work on this more, but I hope to add some updates to this starter soon.

Thanks for checking it out ❤️

**Comment by codesport** [comment]
Hi @notrab,

Thank you so much for the detailed answer and sharing your wisdom!  🎉 💯 

Your reply is so helpful that I'm going to print it out and hang it on my wall.

You've swayed me to go with the Sanity route. The scalability and quick customization makes it a no-brainer. 

> > Users can upload their own artwork for printing on t-shirts!
> 
> I actually started doing something similar whereby users could enter a tweet URL and I'd print it on a tee. I never shipped it. I was too scared there would be legal implications, probably even more so now with Musk on the horizon.

This sounds like super cool project. If you need help reviving it let me know, ok?  Perhaps you could also manually review such orders to make sure the tweets are family-friendly and non-inflammatory.

> > Store sends the image and order to Printful to fulfilment and shipping
> 
> Printful has an API for this. You can submit an image and they return a preview.

Would this be their Mock Up Generator API found at: https://developers.printful.com/docs/#tag/Mockup-Generator-API 
and  https://developers.printful.com/docs/#operation/createGeneratorTask

**Comment by notrab** [comment]
@codesport I'd love to revive the Twitter project!
